### ISSUE TITLE
Help [FIXED]

### ISSUE THREAD

**Issue by AjiHack04** [SomnathDas/TestBottoRe#1]
![Screenshot_2020-11-09-01-24-31-201_com microsoft rdc android](https://user-images.githubusercontent.com/53486952/98481440-cf7e5300-222c-11eb-91d2-82fe936c701a.jpg)
Whyy broo help mee

**Comment by SomnathDas** [comment]
@AjiHack04  , there's no module named youtube-dl , install that module by doing
**npm i youtube-dl** and also make sure you installed ffmpeg, google it for more info 
and remember this repo of mine is for test purpose so i am guaranting you 100% working condition
also, please use POWERSHELL instead of CMD in windows 10
